# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b70da8001a1082caca54a24da9a2bba62e4773e48791089ea5f01cdfa03f19f352ad007a210498a7473930f178a6f6b325ec32ce2a87e124802aa4170182db69

test:
  secret_key_base: b20ae9b76bd8af274646b665fdaf968c52623f3e5e7339335ef4f169795f9a6c215e66907dc43a46e13cea879b16113290e8ca090fac32415f478855badf798f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
